const jobListings = [
  {
    id: 1,
    companyName: "TechFlow Solutions",
    position: "Frontend Developer",
    location: "Remote",
    type: "Full-time",
    salary: "$90,000 - $110,000",
    description:
      "Building responsive React dashboards and optimizing performance.",
    status: "not applied",
  },
  {
    id: 2,
    companyName: "GreenGrid Energy",
    position: "Full Stack Engineer",
    location: "Austin, TX",
    type: "Hybrid",
    salary: "$120,000 - $140,000",
    description:
      "Developing smart grid monitoring tools using Node.js and Vue.",
    status: "not applied",
  },
  {
    id: 3,
    companyName: "CyberShield AI",
    position: "Security Analyst",
    location: "Washington D.C.",
    type: "On-site",
    salary: "$100,000 - $115,000",
    description:
      "Monitoring network traffic and implementing zero-trust protocols.",
    status: "not applied",
  },
  {
    id: 4,
    companyName: "Nova Health",
    position: "UI/UX Designer",
    location: "Remote",
    type: "Contract",
    salary: "$70 - $90 / hr",
    description:
      "Designing patient-facing mobile apps and accessibility systems.",
    status: "not applied",
  },
  {
    id: 5,
    companyName: "SwiftLogistics",
    position: "Backend Developer",
    location: "Chicago, IL",
    type: "Full-time",
    salary: "$110,000 - $130,000",
    description: "Architecting scalable APIs for real-time fleet tracking.",
    status: "not applied",
  },
  {
    id: 6,
    companyName: "BlueSky Media",
    position: "Content Strategist",
    location: "New York, NY",
    type: "Hybrid",
    salary: "$85,000 - $95,000",
    description: "Managing digital campaigns and cross-platform storytelling.",
    status: "not applied",
  },
  {
    id: 7,
    companyName: "Peak Finance",
    position: "Data Scientist",
    location: "San Francisco, CA",
    type: "Full-time",
    salary: "$150,000 - $180,000",
    description:
      "Applying machine learning models to predictive stock analysis.",
    status: "not applied",
  },
  {
    id: 8,
    companyName: "Evergrow EdTech",
    position: "QA Engineer",
    location: "Remote",
    type: "Full-time",
    salary: "$80,000 - $100,000",
    description: "Automating end-to-end testing for online learning platforms.",
    status: "not applied",
  },
];
